### ISSUE TITLE
Incomplete Syntax Highlighting

### ISSUE THREAD

**Issue by geri1701** [exercism/codemirror-lang-gleam#4]
I've noticed an issue with the syntax highlighting when dealing with case statements. While the code displays correctly in my local editor (helix), when viewed on exercism, the highlighting abruptly ends in the middle of a case statement.

Exercism:
![image](https://github.com/exercism/codemirror-lang-gleam/assets/67984144/9277b967-0631-4d81-a0ef-a0d6288efa2b)

Helix Editor:
![image](https://github.com/exercism/codemirror-lang-gleam/assets/67984144/be00dc15-6197-4d83-b57c-e66f984204ba)

**Comment by lpil** [comment]
Thank you . @giacomocavalieri do you know what is happening here off the top of your head? I had a look but couldn't spot the problem.

**Comment by giacomocavalieri** [comment]
The way I wrote the grammar it should break that easily, that's really strange. I could try adding a case for the bit syntax though

**Comment by geri1701** [comment]
Noticed, exercism editor also displays it correctly like my local editor, this issue only occurs in the solution view.

**Comment by giacomocavalieri** [comment]
Aha! Then it's most likely not a problem with the lezer grammar, iirc this is only used in the editor

**Comment by geri1701** [comment]
Thank you very much, I'll close the issue and reopen it in the appropriate place.

**Comment by ErikSchierboom** [comment]
> Noticed, exercism editor also displays it correctly like my local editor, this issue only occurs in the solution view.

That's the highlightjs plugin.
