### ISSUE TITLE
Moving to Codemirror 6 `^6.0.0`

### ISSUE THREAD

**Issue by dem4ron** [exercism/codemirror-lang-gleam#5]
Hey! 
Exercism is [moving to CodeMirror 6 `^6.0.0`](https://github.com/exercism/website/pull/6878). 
This is one of the two packages that needs to be republished with later dependencies. Could someone of the maintainers please help with updating this package to use the latest codemirror dependencies?

Thank you!

**Comment by dem4ron** [comment]
Hey, I've created [this PR](https://github.com/exercism/codemirror-lang-gleam/pull/6) that updates the dependencies of Codemirror.

**Comment by lpil** [comment]
Published! Thank you

**Comment by dem4ron** [comment]
Thank you!
